name: Run Quality Report

on:
  push:
    branches: [ main ]
  workflow_dispatch:


jobs:
  build:
    name: Run Quality Report
    runs-on: macos-14
    permissions:
      contents: write

    steps:
      - name: Add path globally
        run: echo "/usr/local/bin" >> $GITHUB_PATH

      - name: Checkout
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # pin@v4
        with:
          lfs: 'true'

      - name: Build and Test
        run: |
          xcodebuild -scheme Logging-Package test -destination "platform=iOS Simulator,name=iPhone 14,OS=latest" \
            -enableCodeCoverage YES -resultBundlePath result.xcresult
            
      - name: Run SonarCloud Scanning
        run: |
          bash xccov-to-sonarqube-generic.sh result.xcresult/ >Coverage.xml

          brew install sonar-scanner

          sonar-scanner \
            -Dsonar.token=$SONAR_TOKEN \
            -Dsonar.coverageReportPaths="Coverage.xml"
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Increment Version
        id: versioning
        uses: Oliver-Binns/Versioning@4695fba9f63bed5b557094f9a64f7a2b1a7639e8 # pin@v1.1.0
        with:
          ACTION_TYPE: Release
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
